name: PR Notifications to Slack

on:
  issue_comment:
    types: [created]
  pull_request:
    types: [closed]

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Load Slack user map
        id: usermap
        run: |
          echo '${{ secrets.SLACK_USER_MAP }}' > usermap.json

      # --- Khi Dev comment READY ---
      - name: Notify PR Ready
        if: github.event_name == 'issue_comment' && startsWith(github.event.comment.body, 'ready')
        id: ready
        run: |
          body="${{ github.event.comment.body }}"

          # Tách reviewer từ comment (vd: "ready @alice @bob")
          reviewers=$(echo "$body" | grep -o '@[a-zA-Z0-9._-]\+' | tr -d '@')

          mentions=""
          for r in $reviewers; do
            slack_id=$(jq -r --arg user "$r" '.[$user]' usermap.json)
            if [ "$slack_id" != "null" ]; then
              mentions="$mentions <@$slack_id>"
            else
              mentions="$mentions @$r"
            fi
          done

          ts=$(curl -s -X POST \
            -H "Authorization: Bearer $SLACK_BOT_TOKEN" \
            -H 'Content-type: application/json' \
            --data "{
              \"channel\": \"${SLACK_CHANNEL_ID}\",
              \"text\": \"👀 PR Ready for Review $mentions\",
              \"blocks\": [
                {
                  \"type\": \"section\",
                  \"text\": {
                    \"type\": \"mrkdwn\",
                    \"text\": \"*${{ github.event.issue.title }}*\nAuthor: ${{ github.event.comment.user.login }}\nReviewers: $mentions\n<${{ github.event.issue.html_url }}|View PR>\"
                  }
                }
              ]
            }" https://slack.com/api/chat.postMessage | jq -r '.ts')

          echo "thread_ts=$ts" >> $GITHUB_ENV

          # Lưu thread_ts vào PR comment ẩn
          gh api repos/${{ github.repository }}/issues/${{ github.event.issue.number }}/comments \
            -f body="<!-- slack-thread-ts:$ts -->"
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
          SLACK_CHANNEL_ID: ${{ secrets.SLACK_CHANNEL_ID }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # --- Khi Reviewer comment "comment ..."
      - name: Notify Reviewer Feedback
        if: github.event_name == 'issue_comment' && startsWith(github.event.comment.body, 'comment')
        run: |
          # Parse Slack mapping từ secret
          echo '${{ secrets.SLACK_USER_MAP }}' > usermap.json

          # Lấy thread_ts từ PR comment ẩn
          ts=$(gh api repos/${{ github.repository }}/issues/${{ github.event.issue.number }}/comments \
            --jq '.[] | select(.body | contains("slack-thread-ts")) | .body' | \
            sed -n 's/.*slack-thread-ts:\(.*\)-->.*/\1/p' | tail -n1)

          # Author PR
          pr_author="${{ github.event.issue.user.login }}"
          author_id=$(jq -r --arg user "$pr_author" '.[$user]' usermap.json)

          # Reviewer (người comment)
          reviewer="${{ github.event.comment.user.login }}"
          reviewer_id=$(jq -r --arg user "$reviewer" '.[$user]' usermap.json)

          # Build mentions (giống flow ready)
          mentions=""
          if [ "$author_id" != "null" ]; then
            mentions="$mentions <@$author_id>"
          fi
          if [ "$reviewer_id" != "null" ]; then
            mentions="$mentions <@$reviewer_id>"
          fi

          # Gửi reply vào thread
          curl -s -X POST \
            -H "Authorization: Bearer $SLACK_BOT_TOKEN" \
            -H 'Content-type: application/json' \
            --data "{
              \"channel\": \"${SLACK_CHANNEL_ID}\",
              \"thread_ts\": \"$ts\",
              \"text\": \"💬 Review feedback from *$reviewer* $mentions\",
              \"blocks\": [
                {
                  \"type\": \"section\",
                  \"text\": {
                    \"type\": \"mrkdwn\",
                    \"text\": \"*$reviewer* commented:\n>>> ${{ github.event.comment.body }}\n$mentions\n<${{ github.event.comment.html_url }}|View Comment>\"
                  }
                }
              ]
            }" https://slack.com/api/chat.postMessage
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
          SLACK_CHANNEL_ID: ${{ secrets.SLACK_CHANNEL_ID }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # --- Khi PR được merged ---
      - name: Notify Merge
        if: github.event.pull_request.merged == true
        run: |
          echo '${{ secrets.SLACK_USER_MAP }}' > usermap.json

          ts=$(gh api repos/${{ github.repository }}/issues/${{ github.event.pull_request.number }}/comments \
            --jq '.[] | select(.body | contains("slack-thread-ts")) | .body' | \
            sed -n 's/.*slack-thread-ts:\(.*\)-->.*/\1/p' | tail -n1)

          merger="${{ github.event.pull_request.merged_by.login }}"
          merger_id=$(jq -r --arg user "$merger" '.[$user]' usermap.json)

          pr_author="${{ github.event.pull_request.user.login }}"
          author_id=$(jq -r --arg user "$pr_author" '.[$user]' usermap.json)

          mentions="<!channel>"
          if [ "$author_id" != "null" ]; then
            mentions="$mentions <@$author_id>"
          fi
          if [ "$merger_id" != "null" ]; then
            mentions="$mentions <@$merger_id>"
          fi

          curl -s -X POST \
            -H "Authorization: Bearer $SLACK_BOT_TOKEN" \
            -H 'Content-type: application/json' \
            --data "{
              \"channel\": \"${SLACK_CHANNEL_ID}\",
              \"thread_ts\": \"$ts\",
              \"text\": \"✅ PR merged! $mentions\",
              \"blocks\": [
                {
                  \"type\": \"section\",
                  \"text\": {
                    \"type\": \"mrkdwn\",
                    \"text\": \"*${{ github.event.pull_request.title }}* has been merged!\nAuthor: $pr_author\nMerged by: $merger\n$mentions\n<${{ github.event.pull_request.html_url }}|View PR>\"
                  }
                }
              ]
            }" https://slack.com/api/chat.postMessage
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
          SLACK_CHANNEL_ID: ${{ secrets.SLACK_CHANNEL_ID }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}